name: Update Crypto Data
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install yfinance pandas streamlit
          sudo apt-get install -y libgl1-mesa-glx
          
      - name: Run data update
        run: |
          python 02_Crypto_Analysis/scripts/data_fetcher.py
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "🔄 Auto-update crypto data $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
