name: Update Crypto Data
on:
  schedule:
    - cron: '0 12 * * *'  # Executa ao meio-dia UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão para fazer push
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install yfinance pandas plotly streamlit
          pip install nbconvert ipykernel
          
      - name: Execute and Update
        run: |
          # Atualiza dados
          python 02_Crypto_Analysis/scripts/data_fetcher.py
          
          # Gera novo dashboard
          streamlit run 02_Crypto_Analysis/scripts/technical_analysis.py --server.headless true --server.runOnSave true
          
          # Commit e push
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "🔄 Auto-update $(date +'%Y-%m-%d')" || echo "Nenhuma mudança para commitar"
          git push