name: Update Crypto Data
on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia ao meio-dia UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install yfinance pandas plotly nbconvert
      - name: Run Crypto Analysis
        run: |
          jupyter nbconvert --execute 02_Crypto_Analysis/notebooks/crypto_dashboard.ipynb
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "🔄 Auto-update crypto data $(date +'%Y-%m-%d')"
          git push